### ISSUE TITLE
GillesPy 1.0 examples assume the .run argument "show_labels=False" but the updated version sets this by default to true.

### ISSUE THREAD

**Issue by JohnAbel** [JohnAbel/gillespy#23]
I didn't catch this, I just came across a StackOverflow user who caught it.
https://stackoverflow.com/questions/45260533/typeerror-unhashable-type-on-new-computer-but-not-old

**Comment by briandrawert** [comment]
In the 1.1 release, we updated all the examples to work correctly.   What is the correct behavior here?  To access species in PyURDME, you need to know the 'name' not the index of the specie to access it.  When constructing models, we don't provide the index number, just a name.  I guess my vote is to leave 'show_labels' defaulted as True.  However, we should probably fix the examples to reflect this.

**Comment by JohnAbel** [comment]
We fixed this.
