### ISSUE TITLE
Setting the seed

### ISSUE THREAD

**Issue by JohnAbel** [JohnAbel/gillespy#6]
We should discuss this.

**Comment by ahellander** [comment]
What is it that you want to do?

**Comment by JohnAbel** [comment]
The question is one of best practices: if unspecified, should gillespy run a specific seed every time, or should the seed be dynamically generated. I talked to Brian about this but I don't recall the conclusion.

**Comment by ahellander** [comment]
Not obvious, but I think it might be safer to try to pick a dynamically generated one. I think then the risk of modeling errors is slightly smaller. I think user's would expect a different seed? On the other hand, it can be tricky. 

A compromise might be  to use a fixed one the first time a solver or model.run is called, and then generate new ones for each consecutive call to it.

**Comment by briandrawert** [comment]
To stay consistent with StochSS and other stochastic software packages, if a seed is not given, a randomly generated int is used as the see (done in this commit: fac5f5c077e2966849c1afd3af7b0a6c8dfe498c)
