### ISSUE TITLE
Non first-order mass action does not simulate correctly

### ISSUE THREAD

**Issue by JohnAbel** [JohnAbel/gillespy#9]
Example:

```
import numpy as np
import casadi as cs
import gillespy as gsp
import matplotlib.pyplot as plt

class simple_gillespy_model(gsp.Model):

    def __init__(self, volume=100.0):

        #Initialize the model
        gsp.Model.__init__(self,name='simple',volume=volume)

        # Parameters
        K0 = gsp.Parameter(name='K0',expression=1)

        self.add_parameter([K0])

        # Species
        x1 = gsp.Species(name='x1',initial_value = 100)
        x2 = gsp.Species(name='x2',initial_value = 100)

        self.add_species([x1,x2])

        # Reactions
        r1 = gsp.Reaction(name='formation of x1',
                          reactants = {},
                          products={x1:1},
                          propensity_function='K0*vol')

        r2 = gsp.Reaction(name='formation of x2', products={x2:1}, rate=K0)

        self.add_reaction([r1,r2])

if __name__ == '__main__':

    model = simple_gillespy_model()
    print model.listOfReactions['formation of x1'].propensity_function
    print model.listOfReactions['formation of x2'].propensity_function
    traj = gsp.StochKitSolver.run(model,
                                          t=1000,
                                          increment=0.1,
                                          number_of_trajectories=1)[0]

    plt.plot(traj)

```

 Although the propensity functions here are the same, somehow the trajectories are different. The issue is that despite saying the propensity function for r2 was edited to include volume, it wasn't really edited to include volume.

**Comment by JohnAbel** [comment]
where it says : 
```
# Set the volume dependency based on order.
        order = len(self.reactants)
        if order == 2:
            propensity_function += "/vol"
        elif order == 0:
            propensity_function += "*vol"
```
we need to add something to edit "marate" which is currently just a parameter name.

**Comment by ahellander** [comment]
I don't get it. What is not working? Is StochKit even supporting different volumes? Is not the code above from the pyurdme.Model?

**Comment by JohnAbel** [comment]
StochKit is only fed a model-- in the code there is a way to manually tweak
volumes (originally in StochSS), but at this point, it doesn't correctly
work. I haven't checked if this also fails in StochSS or not.

On Thu, Jun 18, 2015 at 1:23 AM, Andreas Hellander <notifications@github.com
> wrote:

> I don't get it. What is not working? Is StochKit even supporting different
> volumes? Is not the code above from the pyurdme.Model?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnAbel/gillespy/issues/9#issuecomment-113073691>.
>



-- 

*John H. Abel*
PhD Candidate, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu
Tel: (401)787-4253

**Comment by JohnAbel** [comment]
This was based on my misunderstanding of where volume is accounted for. I am going to close this since it was my error.
